CLIENT_ID = "2IvMPqBmBBDhl3vBWVbCs4IvqjfQ9AUZ"
CLIENT_SECRET = "lmVks7zDAdyoRQOT"
API_KEY = "v4M5vCGGt0F6tMwxwb2ac5UGENegSS4H"
REDIRECT_URL = "kingswood"
ACCESS_TOKEN = "AZJyWOGjxUVtpGQ2w7jNA9EdWu8O"
REFRESH_TOKEN = "G84Tia8JeST2ELVBqWQWRdZ4cQuqWKZM"

IP = None
PORT = None
USERNAME = None
PASSWORD = None
